homepage/urls.py
from django.urls import path
# from .views import HomePageView
from homepage import views
from django.conf.urls import url

# SET THE NAMESPACE!
app_name = 'homepage'
#urlpatterns = [
#            path('', HomePageView.as_view(), name='home'),
#            ]
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
            url(r'^register/$',views.register,name='register'),
            url(r'^user_login/$',views.user_login,name='user_login'),
            url(r'^reset_password/$',views.reset_password,name='reset_password'),
]

myloginproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from homepage import views
from homepage.views import *
from myloginproject import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

#urlpatterns = [
#    path('admin/', admin.site.urls),
#    path('', include('homepage.urls')),
#    path('accounts/', include('django.contrib.auth.urls')),
#]
urlpatterns = [
            path('admin/', admin.site.urls),
                url(r'^$',views.index,name='index'),
                url(r'^student$',views.index_student,name='index_student'),
                url(r'^professor$',views.index_student,name='index_professor'),
                    url(r'^special/',views.special,name='special'),
                        url(r'^homepage/',include('homepage.urls')),
                            url(r'^logout/$', views.user_logout, name='logout'),
                            url(r'^jobpost/$', views.post_a_job, name='job_form'),
                            url(r'^save_job/$', views.save_job, name='save_job'),
                            url(r'^alljobs/$', views.jobs_list_view, name='jobs_list_view'),
                            url(r'^appliedjobs/$', views.applied_jobs_view, name='applied_jobs_view'),
                            url(r'^delete-jobs/$', views.delete_invalid_jobs, name='delete_invalid_jobs'),
                            path(r'^job_details/<int:id>$',JobDetailsView.as_view(),name='job_details'),
                            # path(r'job_details',views.job_details_view,name='job_details'),
                            path(r'^job_details/<int:user_id>/<int:job_id>$',JobDetailsView.as_view(),name='app_status'),
                            path('apply-job/<int:job_id>', ApplyJobView.as_view(), name='apply-job'),
                            path('delete-job/<int:job_id>', views.delete_job, name='delete-job'),
                             # url(r'^media/profile_pics/(.*.jpeg)$', views.display_image, name='display_image'),
                            url(r'conversation/', include('conversation.urls')),
                            # url(r'^see_conversations/(\d+)/$', views.see_conversations, name='see_conversations'),
                            path(r'see_conversations', views.see_conversations, name='see_conversations'),
                            # url(r'^conversation_form/$', views.conversation_form, name='conversation_form'),
                            url(r'^all_people/$', views.all_people, name='all_people'),
                            # path(r'view_profile/<int:user_id>', views.view_profile, name='view_profile'),
                            path(r'view_profile', views.view_profile, name='view_profile'),
                            url(r'^jobs/$', views.filter_jobs_view, name='jobs'),
                            path(r'update', views.update_profile, name='update_profile'),
                            url(r'^update_profile/$', views.update_profile_in_db, name='update_profile_in_db'),
                            path(r'search_people$', views.search_people, name='search_people'),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/all_applied_jobs.html
{% extends "./base.html" %}
{% load static %}
{% block title %}
    Home
{% endblock %}

{% block body_block %}

        <div class="container">
            <h3 class="heading">Jobs</h3>
            <style type="text/css">
                td
                {
                    padding:0 5px;
                }
            </style>
            <table>
                <tr>
                <form action="{% url 'jobs' %}" method="get">
                    {% csrf_token %}
                    <td><label for="filter"> Jobs Filter </label></td>
                    <td>
                    <select id="filter" name="filter">
                        <option value="All">All</option>
                        <option value="Applied">Applied</option>
                        <option value="University">University</option>
                        <option value="Professor">Professor</option>
                    </select>
                    <input type="submit" value="OK">
                    </td>
                </form>
                </tr>
            </table>

                {% if prof_list %}
                    <table>
                    <tr>
                    <form action="{% url 'jobs' %}" method="get">
                        {% csrf_token %}
                        <td><label for="prof"> Select Professor Name </label></td>
                        <td>
                        <select id="prof" name="prof">
                            {% for entry in prof_list %}
                                <option value="{{ entry.user_id }}">{{ entry.full_name }},{{entry}}</option>
                            {% endfor %}
                        </select>
                        <input type="submit" value="OK">
                        </td>
                    </form>
                    </tr>
                    </table>
                {% elif prof_name %}
                    <p><i>Posted by {{ prof_name }}</i></p>
                {% elif university_list %}
                    <table>
                    <tr>
                    <form action="{% url 'jobs' %}" method="get">
                        {% csrf_token %}
                        <td><label for="university"> Select University </label></td>
                        <td>
                        <select id="university" name="university">
                            {% for entry in university_list %}
                                <option value="{{ entry.name }}">{{ entry.name }}</option>
                            {% endfor %}
                        </select>
                        <input type="submit" value="OK">
                        </td>
                    </form>
                    </tr>
                    </table>
                {% elif university %}
                    <p><i>Posted by {{ university }}</i></p>

                {% elif isempty %}
                    <p><i>No jobs found with this filter</i></p>
                {% endif %}
            {% if filter != None %}
                <p><i>Filter : {{ filter }} </i></p>
            {% else %}
                <p><i>Select a filter</i></p>
            {% endif %}
            {% if alljobs %}
                <div class="row featured align-items-stretch">
                    {% for j in alljobs %}
                        <div class="col-lg-4 mb-5 mb-lg-0">
                            <div class="box-image-text bg-visible full-height">
                                <div class="top">
                                    <a href="#">

    <!--                                     <div class="image">
                                            <img src="{% static 'img/featured1.jpg' %}" alt="" class="img-fluid">
                                        </div> -->
                                        <div class="bg"></div>
                                        <div class="logo">
                                            <img src="{% static 'img/company-1.png' %}" alt="" style="max-width: 80px;">
                                        </div>
                                    </a>
                                </div>
                                <div class="content">
                                    <!-- <p> The job id is {{ job.id }}</p> -->
                                    <!-- <h5><a href ="/job_details/{{job.id}}"> {{ job.title }}</a></h5>    -->
                                    <script type="text/javascript">
                                      function submitJobDetailsForm(n)
                                      {
                                        var f = document.getElementsByName(n)[0];
                                        f.submit();
                                      }
                                    </script>
                                    <form name ="{{j.title}}" action = "{%url 'job_details' 999 %}" method = 'post' enctype="multipart/form-data">
                                          {% csrf_token %}
                                              <input type="hidden" name="job_id" value={{j.id}}>
                                              <input type="hidden" name="details" value="True">
                                              <h5><a href ="javascript: submitJobDetailsForm('{{j.title}}')"> {{ j.title }}</a></h5>
                                    </form>
                                    <!-- <h5><a href ="{% url 'job_details' j.id %}"> {{ j.title }}</a></h5> -->
                                    <p class="featured__details"><i class="fa fa-map-marker job__location"></i>
                                        {{ j.location }}
                                        {% if j.type == '1' %}
                                            <span class="badge featured-badge badge-success">Full time</span>
                                        {% elif j.type == '2' %}
                                            <span class="badge featured-badge badge-primary">Part time</span>
                                        {% else %}
                                            <span style="color: #ffffff;" class="badge featured-badge badge-warning">Internship</span>
                                        {% endif %}
                                    </p>
                                    <p>{{ j.description }}</p>
                                    {% if applied %}
                                         <p>Application Status : {{ j.status }}</p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>

{% endblock %}

templates/all_jobs.html
{% extends "./base.html" %}
{% load static %}
{% block title %}
    Home
{% endblock %}

{% block body_block %}

        <div class="container">
            <h3 class="heading">Jobs</h3>
            <style type="text/css">
                td
                {
                    padding:0 5px;
                }
            </style>
            <table>
                <tr>
                <form action="{% url 'jobs' %}" method="get">
                    {% csrf_token %}
                    <td><label for="filter"> Jobs Filter </label></td>
                    <td>
                    <select id="filter" name="filter">
                        <option value="All">All</option>
                        <option value="Posted by you">Posted by you</option>
                    </select>
                    <input type="submit" value="OK">
                    </td>
                </form>
                </tr>
            </table>
            {% if filter != None %}
                <p><i>Filter : {{ filter }} </i></p>
            {% else %}
                <p><i>Select a filter</i></p>
            {% endif %}
            {% if isempty %}
                <p><i>No jobs found with this filter</i></p>
            {% endif %}
            {% if alljobs %}
                <div class="row featured align-items-stretch">
                    {% for j in alljobs %}
                        <div class="col-lg-4 mb-5 mb-lg-0">
                            <div class="box-image-text bg-visible full-height">
                                <div class="top">
                                    <a href="#">

    <!--                                     <div class="image">
                                            <img src="{% static 'img/featured1.jpg' %}" alt="" class="img-fluid">
                                        </div> -->
                                        <div class="bg"></div>
                                        <div class="logo">
                                            <img src="{% static 'img/company-1.png' %}" alt="" style="max-width: 80px;">
                                        </div>
                                    </a>
                                </div>
                                <div class="content">
                                    <!-- <p> The job id is {{ job.id }}</p> -->
                                    <!-- <h5><a href ="/job_details/{{job.id}}"> {{ job.title }}</a></h5>     -->
                                    <script type="text/javascript">
                                      function submitJobDetailsForm(n)
                                      {
                                        // window.alert(n);
                                        var f = document.getElementsByName(n)[0]
                                        f.submit();
                                      }
                                    </script>
                                    <form name ="{{j}}" action = "{%url 'job_details' 999 %}" method = 'post' enctype="multipart/form-data">
                                          {% csrf_token %}
                                              <input type="hidden" name="job_id" value={{j.id}}>
                                              <input type="hidden" name="details" value="True">
                                              <h5><a href ="javascript: submitJobDetailsForm('{{j}}')"> {{ j.title }}</a></h5>
                                    </form>
                                    <!-- <h5><a href ="{% url 'job_details' j.id %}"> {{ j.title }}</a></h5> -->
                                    <p class="featured__details"><i class="fa fa-map-marker job__location"></i>
                                        {{ j.location }}
                                        {% if j.type == '1' %}
                                            <span class="badge featured-badge badge-success">Full time</span>
                                        {% elif j.type == '2' %}
                                            <span class="badge featured-badge badge-primary">Part time</span>
                                        {% else %}
                                            <span style="color: #ffffff;" class="badge featured-badge badge-warning">Internship</span>
                                        {% endif %}
                                    </p>
                                    <p>{{ j.description }}</p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
	  <head>
		      <meta charset="utf-8">
		          <title>Base</title>
			      <!-- Latest compiled and minified CSS -->
			          <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	  </head>
	    <body>
		        <nav class="navbar navbar-default navbar-static-top">
				      <div class="container">
					              <ul class="nav navbar-nav">
							      {# Django Home Link / Admin Link / Register Link#}
							                <li><a class="navbar-brand" href="{% url 'index' %}">Home</a></li>
									          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
										            <li><a class="navbar-link" href="{% url 'homepage:register' %}">Register</a></li>     
											              {# Some logic on what to display for last item#}
												                {% if user.is_authenticated %}
														            <li><a href="{% url 'logout' %}">Logout</a></li>
															              {% else %}
																                  <li><a class="navbar-link" href="{% url 'homepage:user_login' %}">Login</a></li>
																		            {% endif %}
						      </ul>
						            </div>
							        </nav>
								    <div class="container">
									        {% block body_block %}
										    {% endblock %}
										        </div>
											  </body>
</html>

templates/details.html
    {% extends 'base.html' %}
{% load static %}
{% load is_already_applied %}

{% block title %}
    Job details
{% endblock %}

{% block body_block %}
        <a href = '/jobs'> Go back to all jobs </a>
   
        <div class="container">
            <h1 class="heading">{{ job.title }}<br>
                <small>at <a href="#"> {{ job.workplace_name }}</a></small>
            </h1>
            <div class="job-detail-description"><i class="fa fa-map-marker job__location"> </i>
                    <script type="text/javascript">
                    function visitProfessorProfile()
                        {
                        document.visitProfileForm.submit();
                        }
                    </script>
                <form name="visitProfileForm" action="{% url 'view_profile' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="user_id" value = "{{job.user.id}}">
                      Posted by <a href = 'javascript: visitProfessorProfile()'> {{job.user.myuser.full_name}} </a>
                </form>
                {{ job.location }} | Posted {{ job.created_at|timesince }} |
                {% if job.type == '1' %}
                    <span class="badge featured-badge badge-success">Full time</span>
                {% elif job.type == '2' %}
                    <span class="badge featured-badge badge-primary">Part time</span>
                {% else %}
                    <span style="color: #ffffff;" class="badge featured-badge badge-warning">Internship</span>
                {% endif %}
            </div>
        </div>
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <h3>Category: {{ job.category }}</h3>
                    <h5>Last date: {{ job.last_date|date }}</h5>
                    <h5 class="text-info">Salary: {% if job.salary > 0 %} {{ job.salary }}/Monthly {% else %} Negotiable {% endif %} </h5>
                    <blockquote class="blockquote">
                        <p>{{ job.description }}</p>
                    </blockquote>
                    {% if role == 'Student' %}
                        <div class="job-detail__apply-bottom">
                            {% if request.user.is_authenticated %}
                                {% is_already_applied job request.user as is_applied %}
                                {% if is_applied %}
                                    {% if status == 'In Process' %}
                                        <input type="button" class="btn btn-outline-white-primary" value="Already applied"/>
                                    {% elif status == 'Accept' %}
                                        <input type="button" class="btn btn-outline-white-primary" value='Accepted'/>
                                    {% else %}
                                        <input type="button" class="btn btn-outline-white-primary" value='Rejected'/>
                                    {% endif %}
                                {% else %}
                                    <form action="{% url 'apply-job' job.id %}" method="post">
                                        {% csrf_token %}
                                        <input type="hidden" name="job" value="{{ job.id }}">
                                        <input type="submit" class="btn btn-outline-white-primary"
                                               value="Apply for this job"/>
                                    </form>
                                {% endif %}
                            {% else %}
                                <form action="{% url 'apply-job' job.id %}" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="job" value="{{ job.id }}">
                                    <input type="submit" class="btn btn-outline-white-primary"
                                           value="Apply for this job"/>
                                </form>
                            {% endif %}
                        </div>
                    {% elif role == 'Professor' %}
                      {% if posted %}

                        <form action="{% url 'delete-job' job.id %}" method="post">
                                        {% csrf_token %}
                                        <input type="hidden" name="job" value="{{ job.id }}">
                                        <input type="submit" class="btn btn-outline-white-primary"
                                               value="Delete this job"/>
                        </form>
                        <div class="applicant">

                            {% if applied_data|length %}
                                <h3>Applicant List</h3><br/>
                                <style type="text/css">
                                td,th
                                {
                                    padding:0 5px;
                                }
                                </style>
                                <table>
                                    <tr><th>Applicant</th><th>Decision</th></tr>
                                    {% for application in applied_data %}
                                        <tr>
                                        {% if application.1 == 'In Process' %}

                                                 <script type="text/javascript">
                                                            function submitVisitProfileForm(x)
                                                            {
                                                                // window.alert(x);
                                                                x.submit();
                                                            }
                                                </script>

                                                <form name="{{application.0.user.username}}" action="{% url 'view_profile' %}" method = "POST">
                                                {% csrf_token %}
                                                <input type="hidden" name="user_id" value = "{{application.0.user_id}}"/>
                                                <td><label for="acceptance"> <a href = 'javascript: submitVisitProfileForm({{application.0.user.username}})'> {{ application.0.full_name }} {{application.0.linkedin_url}} </a> </label></td>
                                                </form>
<!--                                                 <td><label for="acceptance"> <a href="/view_profile/{{application.0.user_id}}"> {{ application.0.full_name }} {{application.0.linkedin_url}} </a> </label></td>
                                                <td> -->
                                            <form action="{% url 'app_status' application.0.user_id job.id %}" method="post">
                                                {% csrf_token %}
                                                <td>
                                                <select id="acceptance" name="acceptance">
                                                    <option value="In Process">In Process</option>
                                                    <option value="Accept">Accept</option>
                                                    <option value="Reject">Reject</option>
                                                </select>
                                                <input type="submit" value="OK">
                                                </td>
                                            </form>
                                        {% else %}
                                           <!--  <td><a href="/view_profile/{{application.0.user_id}}"> {{ application.0.full_name }} {{application.0.linkedin_url}} </a></td><td>{{application.1}}</td> -->
                                               <script type="text/javascript">
                                                            function submitVisitProfileForm(x)
                                                            {   
                                                                // window.alert(x);
                                                                x.submit();
                                                            }
                                                </script>
                                             <form name="{{application.0.user.username}}" action="{% url 'view_profile' %}" method="POST">
                                                {% csrf_token %}
                                                <input type="hidden" name="user_id" value = "{{application.0.user_id}}"/>
                                                <td><label for="acceptance"> <a href = 'javascript: submitVisitProfileForm({{application.0.user.username}})'> {{ application.0.full_name }} {{application.0.linkedin_url}}
                                                 </a> </label></td>
                                            </form>
                                                <td>{{application.1}}</td>
                                        {% endif %}
                                        <td>
                                            <!-- <a href='/conversation/create/{{ application.0.user_id }}/'> Chat </a> -->
                                            <script type="text/javascript">
                                                function submitChatForm(x)
                                                {
                                                    x.submit()
                                                }
                                            </script>
                                                <form name ="chat{{application.0.user.username}}" action = "{%url 'conversation_create' %}" method = 'POST'>
                                                {% csrf_token %}

                                                    <input type="hidden" name="other_user_id" value={{application.0.user_id}}>
                                                    <a href='javascript: submitChatForm(chat{{application.0.user.username}})'> Chat </a>

                                                </form>
                                        <td>
                                        </tr>
                                    {% endfor %}
                                </table><br/>
                            {% else %}
                                <h3>No Applicants Matching the Criteria</h3>

                            {% endif %}
                          {% endif %}
                        </div>
                    {% endif %}
                </div>
                <div class="col-lg-1"></div>
                <div class="row">
                    <h4>About {{ job.workplace_name }}</h4>
                    <p class="job-detail__company-description">{{ job.workplace_description }}</p>
                    <p class="job-detail__social social social--outline">
                        <a href="{{ job.website }}" data-toggle="tooltip" data-placement="top" title="Website"
                           class="link">
                            <i class="fa fa-link"></i>
                        </a>
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Twitter" class="twitter">
                            <i class="fa fa-twitter"></i>
                        </a>
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Facebook" class="facebook">
                            <i class="fa fa-facebook"></i>
                        </a>
                    </p>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  <div style="text-align:center">Hi {{ user.username }}! Welocme to Coding Infinite!!</div>
  <img src = "{{ user.UserProfileInfo.profile_pic }}" width = "240" />
    <p><a href="{% url 'logout' %}">logout</a></p>
    {% else %}
      <p>You are not logged in</p>
        <a href="{% url 'login' %}">login</a>
	{% endif %}
	{% endblock %}

templates/index.html
{% extends "./base.html" %}
{% block body_block %}
<div class="container">
	  <div class="jumbotron">
	          {% if user.is_authenticated %}
		      	<h1>Welcome to ResearchMatch at {{ user.myuser.university }}</h1>
		      {% else %}
		       	<h1>Welcome to ResearchMatch</h1>
		      {% endif %}
		          {% if user.is_authenticated %}
		          	<form action = "{% url 'search_people' %}" method = 'POST'>
      					{% csrf_token %}
      					<input type="text" name="search_bar"/>
      					<input type="submit" name="submit_botton" value = "search">
		          	</form>
		          	<script type="text/javascript">
						function submitVisitProfileForm()
						{
						  document.visitProfileForm.submit();
						}

						function submitSeeConversationsForm()
						{
						  document.seeConversationsForm.submit();
						}
					</script>

			          <h2>Hello {{ user.myuser.full_name }}</h2>
					<form name="visitProfileForm" action="{% url 'view_profile' %}">
					{% csrf_token %}
  			          <a href = 'javascript: submitVisitProfileForm()'> Visit Profile </a>
  			        </form>
     		          {% if user.myuser.role == "Student" %}
		  				{% if alljobs|length %}
       		          		<h5> <a href = '/jobs' > Jobs </a> </h5>
		  				{% else %}
		  					<h5>No jobs posted</h5>
		  				{% endif %}
       		          {% else %}
       		          	<h5> <a href = '/jobpost/' >Post a job </a> </h5>
		  				{% if alljobs|length %}
       		          		<h5> <a href = '/jobs' > Jobs </a> </h5>
		  				{% else %}
		  					<h5>No jobs posted</h5>
		  				{% endif %}
					  {% endif %}
  					<form name="seeConversationsForm" action="{% url 'see_conversations' %}">
					{% csrf_token %}  			          
  			          <a href = 'javascript: submitSeeConversationsForm()'>See all conversations </a>
  			        </form>
    		         <br/>       		          
		          {% endif %}
						    </div>
</div>
{% endblock %}

templates/login.html
{% extends './base.html' %}
{% block body_block %}
  <div class="container">
	      <div class="jumbotron">
			  	<h1>Login here :</h1>
			    <form method="post" action="{% url 'homepage:user_login' %}">
					  {% csrf_token %}
					  {# A more "HTML" way of creating the login form#}
						<label for="username">Username:</label>
						<input type="text" name="username" placeholder="Username">
						<br/>
						<label for="password">Password:</label>
						<input type="password" name="password" placeholder="Password">
						<br/>
						<input type="submit" name="" value="Login">
			    </form>
			  	<br/>
			  	<a href ="{% url 'homepage:reset_password' %}">Forgot password</a>
	      </div>
  </div>
{% endblock %}